# Site settings
language: 'en-in'
timezone: Asia/Kolkata

title: Ram Iyer’s Résumé
name: Ramakrishnan Iyer
email: ram.iyer@outlook.com
description:

baseurl: /
url: "//resume.ramiyer.me" # the base hostname & protocol for your site
twitter_username: theramiyer
github_username:  theramiyer

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  input: GFM
