# Site settings
timezone: Asia/Kolkata

# Your details
title: Ram Iyer’s Résumé
description: Ram Iyer’s online résumé

name: "Ramakrishnan R.&hairsp;Iyer" # Your full name here
address: "202, Siri Fortune, 18<sup>th</sup> Cross, Purnapragna Layout, Bangalore, KA 560061"
email: "&#99;&#97;&#114;&#101;&#101;&#114;&#64;&#114;&#97;&#109;&#105;&#121;&#101;&#114;&#46;&#105;&#111;" # Encoded in order to prevent spam
phone: "&#43;&#57;&#49;&#57;&#57;&#48;&#49;&#57;&#55;&#53;&#50;&#54;&#55;"
website: ramiyer.io

download: "https://github.com/theramiyer/human-resume-latex/releases/latest/download/Ram.Iyer.pdf"

summary: I am an _Automation Specialist_, drawn to simplifying operations. I specialise in IT Infrastructure Automation, including end-to-end automated server build workflow. I am also a _published co-author_ of a book on PowerShell.

baseurl: /
url: "//resume.ramiyer.io" # the base hostname & protocol for your site
twitter_username: theramiyer
github_username:  theramiyer

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM

# Permalinks
permalink: :title

collections_dir: data
collections:
  experience:
    name: Experience
    output: true
    permalink: /:collection/:name/
    sequence: 1
  certifications:
    name: Certifications
    output: true
    permalink: /:collection/:name/
    sequence: 2
  off-work:
    name: Off-work
    output: true
    permalink: /:collection/:name/
    sequence: 3
  education:
    name: Education
    output: true
    permalink: /:collection/:name/
    sequence: 4
