# Site settings
language: 'en-in'
timezone: Asia/Kolkata

# Your details
title: Ram Iyer’s Résumé
description: Ram Iyer’s Résumé

name: Ramakrishnan R. Iyer
email: ram.iyer@outlook.com
phone: "+918861065751"
address: "513, 19<sup>th</sup> Cross, Purnapragna Layout, Bangalore, KA 560061"

baseurl: /
url: "//resume.ramiyer.me" # the base hostname & protocol for your site
twitter_username: theramiyer
github_username:  theramiyer

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  input: GFM

# Permalinks
permalink: /:categories/:title
